export const ROUTES = {
    HOME: '/',
    JOBS: '/jobs',
    JOB_DETAILS: '/find-jobs/:id',
    PROFILE: '/profile',
    LOGIN: '/login',
    REGISTER: '/register',
    REGISTER_JOBSEEKER: '/register/jobseeker',
    REGISTER_EMPLOYER: '/register/employer',
    CONTACT_US: '/contact-us',
    PROFILE_SETUP: '/profile-setup',
    JOBSEEKER_DASHBOARD: '/jobseeker/overview',
    CV_BUILDER: '/jobseeker/cv-builder',
    JOBSEEKER_PROFILE: '/jobseeker/profile',
    MY_CVS: '/jobseeker/my-cvs',
    APPLICATION_STATUS: '/jobseeker/status',
    JOBSEEKER_FIND_JOBS: '/jobseeker/find-jobs',
    SAVED_JOBS: '/jobseeker/saved-jobs',
    EMPLOYER_DASHBOARD: '/dashboard/employer',
    JOB_MANAGEMENT: '/dashboard/employer/job-management',
    EMPLOYER_APPLICATIONS: '/dashboard/employer/applications',
    EMPLOYER_COMPANY_PROFILE: '/dashboard/employer/company-profile',
    EMPLOYER_HISTORY: '/dashboard/employer/history',
    LOGOUT_CONFIRMATION: '/logout-confirmation',
    NOT_FOUND: '*',
};
