export const API_ENDPOINTS = {
    AUTH: {
        LOGIN: '/auth/login',
        REGISTER_JOB_SEEKER: '/auth/register/job-seeker',
        REGISTER_EMPLOYER: '/auth/register/employer',
        LOGOUT: '/auth/logout',
        ME: '/auth/me',
    },
    JOBS: {
        LIST: '/jobs',
        DETAILS: (id) => `/jobs/${id}`,
        APPLY: (id) => `/jobs/${id}/apply`,
        CREATE: '/jobs',
        UPDATE: (id) => `/jobs/${id}`,
        DELETE: (id) => `/jobs/${id}`,
    },
    CV: {
        LIST: '/cvs',
        GENERATE: '/cvs',
        UPLOAD: '/cvs/upload',
        DETAILS: (id) => `/cvs/${id}`,
        UPDATE: (id) => `/cvs/${id}`,
        DELETE: (id) => `/cvs/${id}`,
        DOWNLOAD: (id) => `/cvs/${id}/download`,
    },
    PROFILE: {
        GET: '/job-seekers/me',
        UPDATE: '/job-seekers/me',
        STATS: '/job-seekers/me/stats',
        MY_APPLICATIONS: '/job-seekers/me/applications',
        SAVED_JOBS: '/job-seekers/me/saved-jobs',
        SAVE_JOB: (id) => `/job-seekers/me/saved-jobs/${id}`,
        UNSAVE_JOB: (id) => `/job-seekers/me/saved-jobs/${id}`,
    },
    EMPLOYER: {
        APPLICATIONS: '/employers/applications',
        JOBS: '/employers/my-jobs',
        STATS: '/employers/me/stats',
        COMPANY_GET: '/employers/profile',
        COMPANY_UPDATE: '/employers/profile',
    },
    ADMIN: {
        STATS: '/admin/stats',
        EMPLOYERS: '/admin/employers',
        EMPLOYER_JOBS: (id) => `/admin/employers/${id}/jobs`,
        DELETE_EMPLOYER: (id) => `/admin/employers/${id}`,
        JOBS: '/admin/jobs',
        JOB_SEEKERS: '/admin/job-seekers',
        VERIFY_EMPLOYER: (id) => `/admin/verify-employer/${id}`,
        BAN_JOB: (id) => `/admin/ban-job/${id}`,
    },
};

